<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as BaseVerifier;

class VerifyCsrfToken extends BaseVerifier
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        '/api/v0.3/*',
        '/vi-tri/get',
        '/vi-tri/set',
        '/vi-tri/timkiem',
        '/congtacvien/dangky',
        '/congtacvien/danhsach',
        '/dangnhapcongtac',
        '/dangnhapcongtac',
        '/lich-su-nap-tien',
        '/nap-tien-vao-vi',
        '/kiem-tra-vi-tien',
        '/check-account-exist',
        '/dang-nhap-mobile',
        '/times-call',
        '/times-call-v2',
        '/times-call-v2-userid',
        '/test-mobile',
        '/facebook-callback',
        '/apiapp',
        '/apiappfacebook',
        '/dangkyapp',
        '/infodoctor',
        '/apilistkhuyenmai',
        '/check/existphone',
        '/api/chuyen-khoa',
        '/api/danh-sach/bac-si',
        '/api/danh-sach/phong-kham',
        '/api/doi-mat-khau',
        '/api/danh-sach/tinh-thanh',
        '/api/thanh-toan-tin-nhan',
        '/api/thanh-toan-tin-nhan-2', 
        '/apihoibacsi/datcauhoi',
        '/apihoibacsi/danhsach',
        '/apihoibacsi/danhsachcauchuatraloi',
        '/apihoibacsi/traloicauhoi',
        '/apihoibacsi/danhsachbinhluan',
        '/api/upload-image',
        '/api/v0.1/appointment_schedule',
        '/api/v0.1/doctor/update/timework',
        '/api/v0.1/doctor/get/timework',
        '/api/v0.1/notify/get',
        '/api/v0.1/notify/add',
        '/api/v0.1/notify/upload-image',
        '/api/v0.1/clinical_achievements/get',
        '/api/v0.1/clinical_achievements/add',
        '/api/v0.1/clinical_achievements/remove',
        '/api/v0.1/clinical_achievements/upload-image',
        '/api/v0.1/clinical_achievements/upload-images',
        '/dang-ky-bac-si',
        '/api/v2/dang-nhap-mobile',
        '/api/v2/dang-ky-mobile',
        '/api/v2/bac-si',
        '/api/v2/bac-si-yeu-thich',
        '/api/v2/bac-si-cua-toi',
        '/api/v2/lich-nhac',
        '/api/v2/lich-nhac-chi-tiet',
        '/api/v2/tintuc-mobile',
        '/api/v2/tintuc-mobile-chitiet',
        '/api/v2/hoi-dap',
        '/chatapi/send-message',
        '/chatapi/get-messages',
        '/chatapi/get-avatar',
        '/chatapi/get-list-rooms',
        '/chatapi/get-list-rooms-update',
        '/chatapi/update-message-status',
        '/chatapi/get-list-doctor-rooms',
        '/chatapi/add-doctor-rooms',
        '/chatapi/get-user',
        '/chatapi/update-useragent',
        '/chatapi/get-token',
        '/chatapi/update-token',
        '/chatapi/send-push-message',
        '/chatapi/get-agora-token',
        '/benhan',
        '/chuyen_benhan',
        '/sua-comment',
        '/tao-tai-khoan',
    ];
}
